catalogs:
  tpcds: |
    connector.name=tpcds  
  tpch: |
    connector.name=tpch
  jmx: |
    connector.name=jmx
  postgres: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgresql.cupdzjlj8tpf.eu-west-2.rds.amazonaws.com:5432/stsfourtwseven
    connection-user=postgres
    connection-password=Starburst
