catalogs:
  tpcds: |
    connector.name=tpcds  
  tpch: |
    connector.name=tpch
  jmx: |
    connector.name=jmx
  postgres: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://$YOUR_HOST_HERE:5432/stsfourtwseven
    connection-user=postgres
    connection-password=Starburst
