# 1. Replace <your_dbs_endpoint> with your RDS instance endpoint 
#    (AWS ex. kp-bootcamp.cs8j7iukogcy.us-east-2.rds.amazonaws.com)
#    (Azure ex. kp-bootcamp.postgres.database.azure.com)
# 2. If you are working on labs in Azure then replace <abfs-account> with your blog storage account.
#    (Azure ex. kplab01stg)
# 3. If you are working on labs in Azure then replace <abfs-key> with your blog storage accounts access key.
#    (Azure ex. VEys9BSb2BLAHV/DU4QRfQYxaGpHkJye9MUFAKENOTREAL0StSsX25J6qsfw+80JWBLAHnOww0tZWb930itLLA==)
# 4. If youa re working on the labs in Azure then scroll down to the bottom to alter the comments in the
#    objectStorage section.

# # This affinity will ensure hive is deployed in the base node group.
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: apps
#           operator: In
#           values: 
#           - base

# The tollerance in this YAML is specifically for Azure so it could be removed or commented out
#    for other clouds. However, it also won't hurt to leave since it is just saying to allow somethign
#    if a taint exists and when it doesn't the tollerance does nothing.
# tolerations:
#   - key: "kubernetes.azure.com/scalesetpriority"
#     operator: "Equal"
#     value: "spot"
#     effect: "NoSchedule"

database:
  external:
    driver: org.postgresql.Driver
    jdbcUrl: jdbc.url=jdbc:postgresql://gm-bootcamp.cupdzjlj8tpf.eu-west-2.rds.amazonaws.com:5432/eks_hms
    user: postgres
    password: StarburstR0cks!
  type: external

resources:
  requests:
    memory: "1Gi"
    cpu: 0.25
  limits:
    memory: "1Gi"
    cpu: 1

