

# # This affinity will ensure hive is deployed in the base node group.
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: apps
#           operator: In
#           values: 
#           - base

# The tollerance in this YAML is specifically for Azure so it could be removed or commented out
#    for other clouds. However, it also won't hurt to leave since it is just saying to allow somethign
#    if a taint exists and when it doesn't the tollerance does nothing.
# tolerations:
#   - key: "kubernetes.azure.com/scalesetpriority"
#     operator: "Equal"
#     value: "spot"
#     effect: "NoSchedule"

database:
  external:
    driver: org.postgresql.Driver
    jdbcUrl: jdbc.url=jdbc:postgresql://YOUR_HOSTNAME.com:5432/eks_hms
    user: postgres
    password: YOUR_PASSWORD
  type: external

resources:
  requests:
    memory: "1Gi"
    cpu: 1
  limits:
    memory: "1Gi"
    cpu: 1

